# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2a30fa6e7d2c165a5d7e8e4f845497b569a45c42a02231cd5161ead2c9a6b9450eea0d86f5c67c9445868ba95cde5af22a39b76713fe65bfd5f0ff65ecf406

test:
  secret_key_base: 9bcf9f54d7a46751c30067c06173b31af8ffb5187adcf7153bea9b226502783752ac16fb4307f564c416142d3bc155dd79ee686338bee4870a4942e9b3ac09b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
